/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.*;
import javax.swing.JOptionPane;
/**
 *
 * @author LabRedes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cmdFra.setEnabled(false);
        txtPe1.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumerador1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtDenominador1 = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JComboBox<>();
        txtNumerador2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtDenominador2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumerador3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtDenominador3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmdCalcular = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdFra = new javax.swing.JButton();
        txtPe = new javax.swing.JTextField();
        txtPe1 = new javax.swing.JTextField();
        txtPe2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("OPERACIÓN CON MIXTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 44, 210, 20));
        jPanel1.add(txtNumerador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, 10));
        jPanel1.add(txtDenominador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, -1));

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División" }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 80, -1));
        jPanel1.add(txtNumerador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 60, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 60, 10));
        jPanel1.add(txtDenominador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 60, -1));

        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        txtNumerador3.setEditable(false);
        jPanel1.add(txtNumerador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 60, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 60, 10));

        txtDenominador3.setEditable(false);
        jPanel1.add(txtDenominador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 60, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });

        cmdFra.setText("Convertir Fraccionario");
        cmdFra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdCalcular)
                .addGap(18, 18, 18)
                .addComponent(cmdLimpiar)
                .addGap(34, 34, 34)
                .addComponent(cmdFra, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCalcular)
                    .addComponent(cmdLimpiar)
                    .addComponent(cmdFra))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 380, 70));

        txtPe.setEditable(false);
        jPanel1.add(txtPe, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 30, -1));
        jPanel1.add(txtPe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 30, -1));
        jPanel1.add(txtPe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        int op, n1, n2, n3, d1, d2, d3, p1, p2;
        Fraccionario f1, f2, f3 = null;
        int sw = 1;
        
        txtNumerador3.setText("");
        txtDenominador3.setText("");
        txtPe.setText("");

        if (txtPe1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la primera parte entera", "Error", 2);
            txtPe1.requestFocusInWindow();
            sw = 0;
        }else if (txtNumerador1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el primer numerador", "Error", 2);
            txtNumerador1.requestFocusInWindow();
            sw = 0;
        } else if (txtDenominador1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el primer denominador", "Error", 2);
            txtDenominador1.requestFocusInWindow();
            sw = 0;
        } else if (txtPe2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la parte entera de segunda fraccion", "Error", 2);
            txtPe2.requestFocusInWindow();
            sw = 0;
        } else if (txtNumerador2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite numerador de la segunda fraccion", "Error", 2);
            txtNumerador2.requestFocusInWindow();
            sw = 0;
        } else if (txtDenominador2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite denominador de la segunda fraccion", "Error", 2);
            txtDenominador2.requestFocusInWindow();
            sw = 0;
        } else {
            try {
                p1 = Integer.parseInt(txtPe1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese el primer entero correctamente", "Error", 2);
                txtPe1.requestFocusInWindow();
                txtPe1.selectAll();
                sw = 0;
            }
            try {
                n1 = Integer.parseInt(txtNumerador1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese el primer numerador correctamente", "Error", 2);
                txtNumerador1.requestFocusInWindow();
                txtNumerador1.selectAll();
                sw = 0;
            }
            try {
                d1 = Integer.parseInt(txtDenominador1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese el primer denominador correctamente", "Error", 2);
                txtDenominador1.requestFocusInWindow();
                txtDenominador1.selectAll();
                sw = 0;
            }
            try {
                p2 = Integer.parseInt(txtPe2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese el entero de segunda fraccion correctamente", "Error", 2);
                txtPe2.requestFocusInWindow();
                txtPe2.selectAll();
                sw = 0;
            }
            try {
                n2 = Integer.parseInt(txtNumerador2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese numerador de la segunda fraccion correctamente", "Error", 2);
                txtNumerador2.requestFocusInWindow();
                txtNumerador2.selectAll();
                sw = 0;
            }
            try {
                d2 = Integer.parseInt(txtDenominador2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Operacion invalida", "Error", 2);
                txtDenominador2.requestFocusInWindow();
                txtDenominador2.selectAll();
                sw = 0;
            }
        }
        if (sw == 1) {
            p1 = Integer.parseInt(txtPe1.getText());
            p2 = Integer.parseInt(txtPe2.getText());
            n1 = Integer.parseInt(txtNumerador1.getText());
            d1 = Integer.parseInt(txtDenominador1.getText());
            n2 = Integer.parseInt(txtNumerador2.getText());
            d2 = Integer.parseInt(txtDenominador2.getText());
            op = cmbOperacion.getSelectedIndex();
            try {
                f1 = new Fraccionario(p1, n1, d1);
                f2 = new Fraccionario(p2, n2, d2);

                switch (op) {
                    case 0:
                    f3 = f1.suma(f2);
                    break;
                    case 1:
                    f3 = f1.resta(f2);
                    break;
                    case 2:
                    f3 = f1.multiplicacion(f2);
                    break;
                    case 3:
                    f3 = f1.division(f2);
                    break;
                }
                txtPe.setText("" + f3.getParte_entera());
                txtNumerador3.setText("" + f3.getNumerador());
                txtDenominador3.setText("" + f3.getDenominador());
                cmdFra.setEnabled(true);
            } catch (DenominadorCeroException e) {
                Helper.mensaje(null, "No puede digitar cero de denominador", "Error", 2);
            }
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtPe1.setText("");
        txtPe2.setText("");
        txtNumerador1.setText("");
        txtNumerador2.setText("");
        txtNumerador3.setText("");
        txtDenominador1.setText("");
        txtDenominador2.setText("");
        txtDenominador3.setText("");
        txtPe1.requestFocusInWindow();
        txtPe.setText("");
        cmbOperacion.setSelectedIndex(0);
        cmdFra.setEnabled(false);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdFraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFraActionPerformed
        // TODO add your handling code here:
        int num,den,ent, n3, d3, Pe;
        
        n3 = Integer.parseInt(txtNumerador3.getText());
        d3 = Integer.parseInt(txtDenominador3.getText());
        Pe = Integer.parseInt(txtPe.getText());
        num=(Pe*d3)+n3;
        den=d3;
        txtPe.setText("");
        txtNumerador3.setText("" + num);
        txtDenominador3.setText("" + den);
        txtPe1.requestFocusInWindow();
        cmdFra.setEnabled(false);
    }//GEN-LAST:event_cmdFraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdFra;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtDenominador1;
    private javax.swing.JTextField txtDenominador2;
    private javax.swing.JTextField txtDenominador3;
    private javax.swing.JTextField txtNumerador1;
    private javax.swing.JTextField txtNumerador2;
    private javax.swing.JTextField txtNumerador3;
    private javax.swing.JTextField txtPe;
    private javax.swing.JTextField txtPe1;
    private javax.swing.JTextField txtPe2;
    // End of variables declaration//GEN-END:variables
}
